# Generated by Django 3.2.3 on 2021-06-28 14:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('dateStart', models.DateField(default=datetime.datetime(2021, 6, 28, 17, 51, 43, 204898))),
                ('dateEnd', models.DateField(default=datetime.datetime(2021, 6, 28, 17, 51, 43, 204898))),
                ('desc', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=1024)),
                ('type', models.CharField(choices=[('1', 'Text'), ('2', 'Select'), ('3', 'Select_multiple')], default='Select', max_length=20)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveyApp.survey')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField(unique=True)),
                ('text', models.CharField(blank=True, max_length=1024, null=True)),
                ('choice', models.CharField(choices=[('1', 'yes'), ('2', 'no')], default='yes', max_length=20)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveyApp.question')),
            ],
        ),
    ]
