# Generated by Django 3.2.3 on 2021-06-28 14:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveyApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='dateEnd',
            field=models.DateField(default=datetime.datetime(2021, 6, 28, 17, 59, 11, 766549)),
        ),
        migrations.AlterField(
            model_name='survey',
            name='dateStart',
            field=models.DateField(default=datetime.datetime(2021, 6, 28, 17, 59, 11, 766549)),
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1024)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveyApp.question')),
            ],
        ),
        migrations.AlterField(
            model_name='answer',
            name='choice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='surveyApp.choice', verbose_name='Chosen option'),
        ),
    ]
