# Generated by Django 3.2.3 on 2021-06-28 18:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveyApp', '0003_auto_20210628_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='dateEnd',
            field=models.DateField(default=datetime.datetime(2021, 6, 28, 21, 11, 54, 969070)),
        ),
        migrations.AlterField(
            model_name='survey',
            name='dateStart',
            field=models.DateField(default=datetime.datetime(2021, 6, 28, 21, 11, 54, 969070)),
        ),
    ]
