# Generated by Django 3.2.3 on 2021-06-28 23:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveyApp', '0004_auto_20210628_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='surveyApp.question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='surveyApp.survey'),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('1', 'Text'), ('2', 'Select'), ('3', 'Select Multiple')], default='Select', max_length=20),
        ),
        migrations.AlterField(
            model_name='survey',
            name='dateEnd',
            field=models.DateField(default=datetime.datetime(2021, 6, 29, 2, 17, 27, 278184)),
        ),
        migrations.AlterField(
            model_name='survey',
            name='dateStart',
            field=models.DateField(default=datetime.datetime(2021, 6, 29, 2, 17, 27, 278184), editable=False),
        ),
    ]
