# Generated by Django 3.2.3 on 2021-06-29 00:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveyApp', '0005_auto_20210629_0217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='dateEnd',
            field=models.DateField(default=datetime.datetime(2021, 6, 29, 3, 1, 51, 407414)),
        ),
        migrations.AlterField(
            model_name='survey',
            name='dateStart',
            field=models.DateField(default=datetime.datetime(2021, 6, 29, 3, 1, 51, 407414), editable=False),
        ),
    ]
